openapi: 3.0.0
info:
  version: 1.0.0
  title: 06-Jobs-API
servers:
  - url: 'https://jobs-api-23vq.onrender.com/api/v1'
    description: Server 1
paths:
  /auth/register:
    post:
      tags:
        - default
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: peter
                email: peter18@gmail.com
                password: secret
            examples:
              default:
                value:
                  name: peter
                  email: peter18@gmail.com
                  password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      security: []
      servers:
        - url: 'https://jobs-api-23vq.onrender.com/api/v1'
          description: Server 1
  /auth/login:
    post:
      tags:
        - default
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: anna14@gmail.com
                password: secret
            examples:
              default:
                value:
                  email: anna14@gmail.com
                  password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      security: []
      servers:
        - url: 'https://jobs-api-23vq.onrender.com/'
          description: Server 1
  /jobs/create:
    post:
      tags:
        - default
      summary: Create Job
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVjNjllNmRjM2JjOTU1ZTc3ZTRiNjMiLCJuYW1lIjoiYW5uYSIsImlhdCI6MTc1MDg4Njg5OSwiZXhwIjoxNzUzNDc4ODk5fQ.wRfIQxdqOY3ghbtGZcnxxCmUnXT4wivmedua1MCxxpA
          examples:
            default:
              value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVjNjllNmRjM2JjOTU1ZTc3ZTRiNjMiLCJuYW1lIjoiYW5uYSIsImlhdCI6MTc1MDg4Njg5OSwiZXhwIjoxNzUzNDc4ODk5fQ.wRfIQxdqOY3ghbtGZcnxxCmUnXT4wivmedua1MCxxpA
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: HEB
                position: produce
            examples:
              default:
                value:
                  company: HEB
                  position: produce
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      security:
        - {}
      servers:
        - url: 'https://jobs-api-23vq.onrender.com/'
          description: Server 1
    get:
      tags:
        - default
      summary: Get All Jobs
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVkYTk1NjMzM2MyZTAwNzVmMGE2MTEiLCJuYW1lIjoicGV0ZXIiLCJpYXQiOjE3NTA5Njg2NzMsImV4cCI6MTc1MzU2MDY3M30.CjU5mSucqRvjBUjOZw3JcuwM1LSR-AXzgCEtLpPGvsc
          examples:
            default:
              value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVkYTk1NjMzM2MyZTAwNzVmMGE2MTEiLCJuYW1lIjoicGV0ZXIiLCJpYXQiOjE3NTA5Njg2NzMsImV4cCI6MTc1MzU2MDY3M30.CjU5mSucqRvjBUjOZw3JcuwM1LSR-AXzgCEtLpPGvsc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      security:
        - {}
      servers:
        - url: 'https://jobs-api-23vq.onrender.com/'
          description: Server 1
  '/jobs/{jobId}':
    get:
      tags:
        - default
      summary: Get Single Job
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
            example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVjYzk3NmIwZjA5ODI2MjljYWRkZGYiLCJuYW1lIjoicGV0ZXIiLCJpYXQiOjE3NTA5MTEzNTAsImV4cCI6MTc1MzUwMzM1MH0.c3rEEBzTV0WlsGUMWGGs9OW3FJ9GkGfzECFbI327Zpo
          examples:
            default:
              value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVjYzk3NmIwZjA5ODI2MjljYWRkZGYiLCJuYW1lIjoicGV0ZXIiLCJpYXQiOjE3NTA5MTEzNTAsImV4cCI6MTc1MzUwMzM1MH0.c3rEEBzTV0WlsGUMWGGs9OW3FJ9GkGfzECFbI327Zpo
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      security:
        - {}
      servers:
        - url: 'https://jobs-api-23vq.onrender.com/'
          description: Server 1
  '/jobs/685dc67f52de91e5bc15c6a4/{jobId}':
    patch:
      tags:
        - default
      summary: Update Job
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: HEB Random
                position: full stack developer
            examples:
              default:
                value:
                  company: HEB Random
                  position: full stack developer
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      security:
        - {}
      servers:
        - url: 'https://jobs-api-23vq.onrender.com/'
          description: Server 1
    delete:
      tags:
        - default
      summary: Delete Job
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      security:
        - {}
      servers:
        - url: 'https://jobs-api-23vq.onrender.com/'
          description: Server 1
components:
  securitySchemes:
    bearerAuth:
      type: oauth2
      flows: {}
